### ISSUE TITLE
New PyPI Release?

### ISSUE THREAD

**Issue by mkoistinen** [ella/django-appdata#10]
Hi, I'm struggling to get a project off the ground. The project depends on another project, which ultimately depends on django-appdata. Was going fine, until we ran Python 3.x tests. Turns out, appdata version 0.1.3 is not really Py3 compatible. I know these issues have been fixed, because my project works if I force install django-appdata from the tip of the repo. Unfortunately, since its not yet in PyPI, I don't know how to get my project to test cleanly on Travis (or other) without cheating. Then, eventually, our users will run into the same issue anyway.

Is there anyway we could get a new release to PyPI that at least tests cleanly on Py3? It'd be a huge help to us.

Many thanks!

(just tagging some others from my team here: @evildmp, @yakky)

**Comment by mkoistinen** [comment]
Is there anything I can do to help get a PyPI release?

**Comment by kvbik** [comment]
new version released [1], thx @HonzaKral for fixes, thank you all for using this lib :)

[1] https://pypi.python.org/pypi/django-appdata/0.1.4

**Comment by mkoistinen** [comment]
Thank you!!!
