### ISSUE TITLE
Compatibility problem with Django<3.1

### ISSUE THREAD

**Issue by pakal** [ella/django-appdata#30]
I have a big KeyError "fields" http500 error when using django-appdata (via djangocms_blog), visibly due to this code:

```
        # Django 3.1 always adds the fields attribute to the kwargs
        # and we must remove appdata fields from this list
        kwargs["fields"] = [f for f in fields if '.' not in kwargs["fields"]]
```

I guess kwargs might NOT always contain "fields" in django<3.1, so the lookup should be conditional.

VERSIONS :
django                     3.0.10
django-appdata             0.3.1

**Comment by yakky** [comment]
@pakal this has been fixed in 0.3.2
