### ISSUE TITLE
Django 1.7 deprecates declared_fieldsets

### ISSUE THREAD

**Issue by mtirsel** [ella/django-appdata#5]
I am using appdata in Django 1.7 where declared_fieldsets are now deprecated and will be removed in 1.9. So I tried to use fieldsets directly and it seems that it is working correctly (there is a note in README about validation bug in Django admin) but I don't have enough experiences with Django internals to be 100% sure if it's really ok. If it's true, AppDataAdminMixin._get_form_factory_opts() method can be changed like this:

```python
def _get_form_factory_opts(self, request, obj=None, **kwargs):
    fields = flatten_fieldsets(self.get_fieldsets(request, obj))
    # ...
```

I have a use case where I select some modules from MultipleChoiceField and based on this selection, I hide or display appropriate fieldsets items and this works with get_fieldsets() only.

I could prepare a pull request but I need a little help with:

* this could break the compatibility with older Django versions so it needs to detect the version and use the old or the new way. But something like this (pseudocode) does not smell very well to me, any ideas?

```python
if version >= 1.7:
    # new way
else:
    # old way
```

* Django uses this code to get all fields from fieldsets:

```python
def get_form(self, request, obj=None, **kwargs):
    """
    Returns a Form class for use in the admin add view. This is used by
    add_view and change_view.
    """
    if 'fields' in kwargs:
        fields = kwargs.pop('fields')
    else:
        fields = flatten_fieldsets(self.get_fieldsets(request, obj))
```
appdata does not check fields in kwargs, so I am not sure, if it should be checked or not.

**Comment by kvbik** [comment]
new version released [1], thx @HonzaKral for fixes, thank you all for using this lib :)

[1] https://pypi.python.org/pypi/django-appdata/0.1.4

**Comment by tony** [comment]
It'd be nice to see what the ref was that fixed it
